// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBIaThAvR0Hei6gxXkv_pzlfy6Yqubd-4',
    appId: '1:359895136956:web:e6778d54123d9631276eb9',
    messagingSenderId: '359895136956',
    projectId: 'checkup-43fd5',
    authDomain: 'checkup-43fd5.firebaseapp.com',
    storageBucket: 'checkup-43fd5.firebasestorage.app',
    measurementId: 'G-CEVTWY84F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc07uUIbsA9qVPPWqR7ENENJmAJmjPCzI',
    appId: '1:359895136956:android:9f19b3000a85bead276eb9',
    messagingSenderId: '359895136956',
    projectId: 'checkup-43fd5',
    storageBucket: 'checkup-43fd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcfc3Tb0EFM3fHwxfzsmUrhXywmVl7sUY',
    appId: '1:359895136956:ios:c6b35bc82cfe120c276eb9',
    messagingSenderId: '359895136956',
    projectId: 'checkup-43fd5',
    storageBucket: 'checkup-43fd5.firebasestorage.app',
    iosBundleId: 'com.example.checkupMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcfc3Tb0EFM3fHwxfzsmUrhXywmVl7sUY',
    appId: '1:359895136956:ios:c6b35bc82cfe120c276eb9',
    messagingSenderId: '359895136956',
    projectId: 'checkup-43fd5',
    storageBucket: 'checkup-43fd5.firebasestorage.app',
    iosBundleId: 'com.example.checkupMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBIaThAvR0Hei6gxXkv_pzlfy6Yqubd-4',
    appId: '1:359895136956:web:15d62922dfde9df2276eb9',
    messagingSenderId: '359895136956',
    projectId: 'checkup-43fd5',
    authDomain: 'checkup-43fd5.firebaseapp.com',
    storageBucket: 'checkup-43fd5.firebasestorage.app',
    measurementId: 'G-4NHEBNL0QH',
  );

}